---
title: "PSTAT 194CS: Final Project"
author: "Daneiel Yalew, Matthew Orr, Phillip Tezaur"
date: "2024-05-14"
output: pdf_document
---

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=20)
knitr::opts_chunk$set(fig.height=10)
```


```{r warning=FALSE}
library(igraph)
library(Matrix)

# default margins
def_marg <- c(5.1, 4.1, 4.1, 2.1)
# no margins
no_marg <- c(0, 0, 0, 0)
```

## Import data and convert to igraph object

```{r}
# read in the raw edgelist
epinions.data <- read.table("./data/soc-Epinions1.txt", sep="\t", header=FALSE, 
                            col.names=c('from', 'to'), skip=4)
head(epinions.data)
```

```{r}
epinions <- graph_from_data_frame(epinions.data, directed=TRUE)
epinions
```

## Get and plot induced subgraphs

```{r}
## Generating / plotting random incuded subgraphs
set.seed(999)

plot_subnetwork <- function(sub_network) {
  plot(sub_network,
     vertex.size=2,
     # === vertex label properties
     # === edge properties
     edge.arrow.size=0.5)
}

sub.network1 <- induced_subgraph(epinions, sample(V(epinions), 200))
sub.network2 <- induced_subgraph(epinions, sample(V(epinions), 200))
sub.network3 <- induced_subgraph(epinions, sample(V(epinions), 200))
sub.network4 <- induced_subgraph(epinions, sample(V(epinions), 200))

par(mar=no_marg, mfrow=c(2,2))

plot_subnetwork(sub.network1)
text(-1, 1,"Sub-Network 1",cex=1.5,font=1)
plot_subnetwork(sub.network2)
text(-1, 1,"Sub-Network 2",cex=1.5,font=1)
plot_subnetwork(sub.network3)
text(-1, 1,"Sub-Network 3",cex=1.5,font=1)
# text(-1.75, -1, ~italic("Figure 1"), cex=1.5, font=1)
plot_subnetwork(sub.network4)
text(-1, 1,"Sub-Network 4",cex=1.5,font=1)

par(mar=def_marg, mfrow=c(1,1))
```

## Plot the Adjacency Matrix

_NB: Adjacency matrix is really sparse and we aren't going to reference it._

```{r}
epinions.adj <- as_adj(epinions)
image(Matrix(epinions.adj))
```

## Community Detection and plotting Communities

```{r}
## Community detection + results
# NB: cluster_fast_greedy() only operates on undirected graphs
e.community <- cluster_fast_greedy(as.undirected(epinions))
e.community

largest_communities_sorted <- table(sort(sizes(e.community), decreasing=TRUE))[1:5]

largest_communities_names <- names(largest_communities_sorted)

cat("Length:", length(e.community), "\n")
cat("5 Largest Sizes:", largest_communities_sorted, "\n")
cat("Modularity:", modularity(e.community), "\n")
```


```{r}
# Plotting communities w/ lasso graphic

V(epinions)$community <- e.community$membership

# split vertecies by group membership
groups <- split(V(epinions), e.community$membership)

mycomcols <- c("black", "#D3D3D3", "#88398A", "white", "#562457")
mylabcols <- c("white", "black", "white", "black", "white")

V(epinions)$color <- mycomcols[V(epinions)$community]
V(epinions)$label.color <- mylabcols[V(epinions)$community]

par(mar=no_marg)
layout <- layout_with_fr(epinions)
plot(epinions,
     layout=layout,
     vertex.size = 5,
     vertex.color = V(epinions)$color, 
     vertex.label.color = V(epinions)$label.color, 
     vertex.label.family = "Helvetica",
     vertex.frame.color = "#88398A",
     vertex.label.cex= 0.5,
     edge.color = "gray60",
     edge.arrow.size = 0.2,
     edge.curved = 0.5,
     mark.groups = groups, 
     mark.col="gray90", 
     mark.border="#88398A")
```

```{r}
## Plot of all communities w/ color
vertex_size <- 2
edge_width <- 0.2

layout <- layout_with_fr(epinions)

V(epinions)$community <- e.community$membership
n_comms <- length(unique(e.community$membership))
set.seed(123)  # For reproducibility
color_palette <- rainbow(n_comms)

V(epinions)$color <- color_palette[V(epinions)$community]


plot(epinions,
     layout=layout,
     vertex.size = vertex_size,
     vertex.color = V(epinions)$color, 
     vertex.label = NA,
     vertex.frame.color = NA,
     edge.color = "gray80",
     edge.width = edge_width,
     edge.arrow.size = 0.1,
     edge.curved = 0.1)
```

```{r}
## Plotting largest communities
largest_vertices <- V(epinions)[V(epinions)$community %in% largest_communities_names]

# Create a subgraph of the largest communities
subgraph <- induced_subgraph(epinions, largest_vertices)

# Assign colors to the largest communities
color_palette <- rainbow(length(largest_communities))
V(subgraph)$color <- color_palette[as.factor(V(subgraph)$community)]

# Plot the subgraph
layout <- layout_with_fr(subgraph)

plot(subgraph,
     layout = layout,
     vertex.size = 5,
     vertex.color = V(subgraph)$color, 
     vertex.label = NA,  # Remove labels for clarity
     vertex.frame.color = NA,
     edge.color = "gray80",
     edge.width = 0.5,
     edge.arrow.size = 0.2,
     edge.curved = 0.1)
```

## Network metrics

```{r}
# sort(degree(epinions, mode='all'))

mean_distance(epinions)

edge_density(epinions)

reciprocity(epinions)

transitivity(epinions)

diameter(epinions)

is_connected(epinions, mode="strong")
components(epinions, mode="strong")$no

articulation_points(epinions)
```

### Degree Centrality 

```{r}
par(mar=def_marg)

## NB: Non-zero value can be used for better visualization
min_deg <- 0

# In-degree
# degree(epinions, mode="in")
deg_in <- degree(epinions, mode="in")
hist(deg_in[deg_in >= min_deg],
     probability=TRUE,
     # breaks=1:vcount(epinions)-1, 
     main=paste("In-Degree ≥", min_deg,"histogram"),
     xlab=paste("In-Degree ≥", min_deg))

# Out-degree
deg_out <- degree(epinions, mode="out")
hist(deg_out[deg_out >= min_deg],
     # breaks=1:vcount(epinions)-1, 
     main=paste("Out-Degree ≥", min_deg,"histogram"),
     xlab=paste("Out-Degree ≥", min_deg))

# Combine in-degree and out-degree
deg_all <- degree(epinions, mode="all")
hist(deg_all[deg_all >= min_deg],
     # breaks=1:vcount(epinions)-1, 
     main=paste("All-Degree ≥", min_deg,"histogram"),
     xlab=paste("All-Degree ≥", min_deg))

```

```{r}
par(mar=no_marg)

deg <- degree(epinions, mode="all")
V(epinions)$deg <- deg

# arrange by degree
deg <- sort(deg, decreasing = T, index.return = T)
ndxs <- deg$ix[1:6]  # Get indexes of 5 most central nodes

#coloring 5 most central nodes
V(epinions)$color[V(epinions)[ndxs]] <- "#88398A"

layout <- layout_with_fr(epinions)
plot(epinions,
     layout=layout,
     vertex.size = sqrt(deg$x)+1,
     vertex.color = V(epinions)$color, 
     vertex.label.color = "gray60", 
     vertex.label.family = "Helvetica",
     vertex.frame.color = "#88398A",
     vertex.label.cex= 0.5,
     edge.color = "gray60",
     edge.arrow.size = 0.2,
     edge.curved = 0.5)
```


## Visualizing the dataset, otherwise

```{r fig.width=20, fig.height=10}
plot(epinions,
     layout=layout_with_fr,
     vertex.size=2,
     # === vertex label properties
     vertex.label=NA,
     # === edge properties
     edge.arrow.size=0.5)
```

```{r}
deg <- degree(epinions, mode="all")
in_deg <- degree(epinions, mode="in")
out_deg <- degree(epinions, mode="out")
in_top_nodes <- V(epinions)[order(in_deg, decreasing=TRUE)[1:10]]
out_top_nodes <- V(epinions)[order(out_deg, decreasing=TRUE)[1:10]]
top_nodes <- V(epinions)[order(deg, decreasing=TRUE)[1:10]]
```

```{r}
# Subgraph of top nodes
subgraph_top_nodes <- induced_subgraph(epinions, top_nodes)

plot(subgraph_top_nodes,
     vertex.size=5,
     vertex.color="red",
     edge.arrow.size=0.5,
     main="Subgraph of Top 10 Nodes with Most Edges")
```

```{r}
# High-out-Degree Nodes and Their Neighborhoods
neighborhood <- ego(epinions, order=1, nodes=top_nodes)

# Set up plotting layout
par(mfrow=c(2, 5))

# Plot each neighborhood
for (i in seq_along(neighborhood)) {
  # Extract the current neighborhood
  subgraph <- induced_subgraph(epinions, neighborhood[[i]])
  
  # Set vertex sizes: larger for the central node
  V(subgraph)$size <- ifelse(V(subgraph)$name == top_nodes[i]$name, 30, 3)
  
  # Set vertex colors: central node in red, others in sky blue
  V(subgraph)$color <- ifelse(V(subgraph)$name == top_nodes[i]$name, "red", "skyblue")
  
  # Plot the subgraph
  plot(subgraph,
       vertex.size=V(subgraph)$size,
       vertex.color=V(subgraph)$color,
       vertex.label=NA,
       main=paste("Neighborhood of Node", top_nodes[i]$name))
}
```

```{r}
# High-out-Degree Nodes and Their Neighborhoods
neighborhood <- ego(epinions, order=1, nodes=in_top_nodes)

# Set up plotting layout
par(mfrow=c(2, 5))

# Plot each neighborhood
for (i in seq_along(neighborhood)) {
  # Extract the current neighborhood
  subgraph <- induced_subgraph(epinions, neighborhood[[i]])
  
  # Set vertex sizes: larger for the central node
  V(subgraph)$size <- ifelse(V(subgraph)$name == in_top_nodes[i]$name, 30, 3)
  
  # Set vertex colors: central node in red, others in sky blue
  V(subgraph)$color <- ifelse(V(subgraph)$name == in_top_nodes[i]$name, "red", "skyblue")
  
  # Plot the subgraph
  plot(subgraph,
       vertex.size=V(subgraph)$size,
       vertex.color=V(subgraph)$color,
       vertex.label=NA,
       main=paste("Neighborhood of Node", in_top_nodes[i]$name))
}

```

```{r}
# High-out-Degree Nodes and Their Neighborhoods
neighborhood <- ego(epinions, order=1, nodes=out_top_nodes)

# Set up plotting layout
par(mfrow=c(2, 5))

# Plot each neighborhood
for (i in seq_along(neighborhood)) {
  # Extract the current neighborhood
  subgraph <- induced_subgraph(epinions, neighborhood[[i]])
  
  # Set vertex sizes: larger for the central node
  V(subgraph)$size <- ifelse(V(subgraph)$name == out_top_nodes[i]$name, 30, 3)
  
  # Set vertex colors: central node in red, others in sky blue
  V(subgraph)$color <- ifelse(V(subgraph)$name == out_top_nodes[i]$name, "red", "skyblue")
  
  # Plot the subgraph
  plot(subgraph,
       vertex.size=V(subgraph)$size,
       vertex.color=V(subgraph)$color,
       vertex.label=NA,
       main=paste("Neighborhood of Node", out_top_nodes[i]$name))
}
```


```{r}
#-----------------------------------------------------------------------------
## Community detection + results
# NB: cluster_fast_greedy() only operates on undirected graphs

# Creates a subgraph of nodes sampled randomly
set.seed(321)  # For reproducibility
nodecount <- length(V(epinions)$name)
percent <- 0.9 # remove % of original nodes

epinions_mini <- delete_vertices(epinions, sample(V(epinions)$name,nodecount*percent))

e.community <- cluster_fast_greedy(as.undirected(epinions_mini))
e.community

largest_communities_sorted <- table(sort(sizes(e.community), decreasing=TRUE))[1:5]

largest_communities_names <- names(largest_communities_sorted)

cat("Length:", length(e.community), "\n")
cat("5 Largest Sizes:", largest_communities_sorted, "\n")
cat("Modularity:", modularity(e.community), "\n")
#-----------------------------------------------------------------------------
## Plot of all communities w/ color
vertex_size <- 2
edge_width <- 0.2

layout <- layout_with_fr(epinions_mini)

V(epinions_mini)$community <- e.community$membership
n_comms <- length(unique(e.community$membership))
set.seed(123)  # For reproducibility
color_palette <- sample(rainbow(n_comms))

V(epinions_mini)$color <- color_palette[V(epinions_mini)$community]

plot(epinions_mini, vertex.size=2,vertex.label=NA,edge.arrow.size=0.2,main="Community Detection Plot")

# Plot only large communities in color
color_palette[which(as.vector(table(e.community$membership) < 10))] <- "#CCCCCC"
V(epinions_mini)$color <- color_palette[V(epinions_mini)$community]
plot(epinions_mini, vertex.size=2,vertex.label=NA,edge.arrow.size=0.2,main="Isolated Users vs Large Communities")

# Percent of users that are grey i.e. isolated dots
# print(sum(as.vector(table(e.community$membership) < 10))/length(as.vector(table(e.community$membership) < 10)))
#-----------------------------------------------------------------------------
```

```{r,echo=TRUE}
#-----------------------------------------------------------------------------
# Row sums = Number of outbound connections for each node
# Col sums = Number of inbound connections for each node

# Histogram demonstrates high concentration of points at < 20 trust/trusted
hist(rowSums(as_adj(epinions)),xlim=c(0,40),breaks=1000, main="Outbound Connection Distribution (# of People Users Trusts)")
hist(colSums(as_adj(epinions)),xlim=c(0,40),breaks=2000, main="Inbound Connection Distribution (# of People Trusting User)")

# Density plots for showing approximate distribution
# Similar to above plots but can include entire distribution since its on a log scale, not really necessary since most are near 0
#plot(density(rowSums(as_adj(epinions))), main="Outbound Distribution (# of People They Trust)", log="x")
#plot(density(colSums(as_adj(epinions))), main="Inbound Distribution (# of People Trusting Them)", log="x")

plot(rowSums(as_adj(epinions)), colSums(as_adj(epinions)), ylab="Inbound (# of People Trusting Them)", xlab="Outbound (# of People They Trust)")

#-----------------------------------------------------------------------------
# Unrelated but worth a read: https://en.wikipedia.org/wiki/Friendship_paradox
```

